test_create_bad_host_pattern (api.source.tests_source.SourceTest)
Test a invalid host pattern. ... ok
test_create_bad_port (api.source.tests_source.SourceTest)
-1 is not a valid ssh port. ... ok
test_create_credential_does_not_exist (api.source.tests_source.SourceTest)
A random int is not a valid credential id. ... ok
test_create_credential_not_valid_id (api.source.tests_source.SourceTest)
A random int is not a valid credential id. ... ok
test_create_empty_credentials (api.source.tests_source.SourceTest)
The empty string is not a valid credential list. ... ok
test_create_empty_host (api.source.tests_source.SourceTest)
An empty string is not a host identifier. ... ok
test_create_empty_hosts (api.source.tests_source.SourceTest)
A vcenter source not have empty hosts. ... ok
test_create_hosts_not_array (api.source.tests_source.SourceTest)
Test error when hosts is not an array. ... ok
test_create_hosts_not_array_of_strings (api.source.tests_source.SourceTest)
Test error when hosts is not an array of strings. ... ok
test_create_invalid_cred_type (api.source.tests_source.SourceTest)
A source type and credential type must be the same. ... ok
test_create_invalid_hosts (api.source.tests_source.SourceTest)
Test invalid host patterns. ... ok
test_create_invalid_name (api.source.tests_source.SourceTest)
A create request must have a string name. ... ok
test_create_long_name (api.source.tests_source.SourceTest)
An long source name. ... ok
test_create_multiple_hosts (api.source.tests_source.SourceTest)
A valid create request with two hosts. ... FAIL
test_create_negative_port (api.source.tests_source.SourceTest)
An long source name. ... ok
test_create_no_credentials (api.source.tests_source.SourceTest)
A Source needs credentials. ... ok
test_create_no_host (api.source.tests_source.SourceTest)
A Source needs a host. ... ok
test_create_no_name (api.source.tests_source.SourceTest)
A create request must have a name. ... ok
test_create_req_host (api.source.tests_source.SourceTest)
A vcenter source must have a host. ... ok
test_create_req_type (api.source.tests_source.SourceTest)
A vcenter source must have an type. ... ok
test_create_sat_with_host_range (api.source.tests_source.SourceTest)
A vcenter source must not have multiple hosts. ... ok
test_create_sat_with_hosts (api.source.tests_source.SourceTest)
A satellite source must not have multiple hosts. ... ok
test_create_too_many_creds (api.source.tests_source.SourceTest)
A vcenter source and have one credential. ... ok
test_create_unprintable_name (api.source.tests_source.SourceTest)
The Source name must be printable. ... ok
test_create_valid_hosts (api.source.tests_source.SourceTest)
Test valid host patterns. ... FAIL
test_create_vc_with_host_range (api.source.tests_source.SourceTest)
A vcenter source must not have multiple hosts. ... ok
test_create_vc_with_hosts (api.source.tests_source.SourceTest)
A vcenter source must not have multiple hosts. ... ok
test_create_with_options_not_allowed_network_type (api.source.tests_source.SourceTest)
Test network type doesn't allow ssl options. ... ok
test_delete (api.source.tests_source.SourceTest)
Delete a Source. ... FAIL
test_delete_with_scans (api.source.tests_source.SourceTest)
Delete a Source used by a scan. ... ok
test_double_create (api.source.tests_source.SourceTest)
A duplicate create should fail. ... FAIL
test_filter_by_type_list (api.source.tests_source.SourceTest)
List all Source objects filtered by type. ... FAIL
test_format_source (api.source.tests_source.SourceTest)
Test the format source method. ... INFO Job 1 (connect, elapsed_time: 0s) - STATE UPDATE (pending)
INFO Task 1 (connect, network, source1, elapsed_time: 0s) - Stats: systems_count=10, systems_scanned=9, systems_failed=1, systems_unreachable=0
ok
test_list (api.source.tests_source.SourceTest)
List all Source objects. ... FAIL
test_partial_update (api.source.tests_source.SourceTest)
Partially update a Source. ... FAIL
test_partial_update_empty_hosts (api.source.tests_source.SourceTest)
Partial update should succeed with missing hosts. ... FAIL
test_partial_update_missing_hosts (api.source.tests_source.SourceTest)
Partial update should succeed with missing hosts. ... FAIL
test_partial_update_network_ssl_options_not_allowed (api.source.tests_source.SourceTest)
Partial update should succeed with missing hosts. ... FAIL
test_partial_update_no_hosts_retains_initial_host (api.source.tests_source.SourceTest)
Partial update should keep initial host if no host provided. ... FAIL
test_retrieve (api.source.tests_source.SourceTest)
Get details on a specific Source by primary key. ... FAIL
test_retrieve_bad_id (api.source.tests_source.SourceTest)
Get details on a specific Source by bad primary key. ... ok
test_sat_req_empty_hosts (api.source.tests_source.SourceTest)
A satellite source must not have empty hosts. ... ok
test_sat_req_host (api.source.tests_source.SourceTest)
A satellite source must have a host. ... ok
test_sat_too_many_creds (api.source.tests_source.SourceTest)
A sat source and have one credential. ... ok
test_source_create_with_false_scan (api.source.tests_source.SourceTest)
Test creating a source with a valid scan query param of False. ... FAIL
test_source_create_with_invalid_scan (api.source.tests_source.SourceTest)
Test the source create method with invalid query param. ... ok
test_source_create_with_true_scan (api.source.tests_source.SourceTest)
Test creating source with valid scan query param of True. ... FAIL
test_successful_net_create (api.source.tests_source.SourceTest)
A valid create request should succeed. ... FAIL
test_successful_net_create_no_port (api.source.tests_source.SourceTest)
A valid create request should succeed without port. ... FAIL
test_successful_sat_create (api.source.tests_source.SourceTest)
A valid create request should succeed. ... FAIL
test_successful_sat_create_with_options (api.source.tests_source.SourceTest)
A valid create request should succeed. ... FAIL
test_successful_vc_create (api.source.tests_source.SourceTest)
A valid create request should succeed. ... FAIL
test_update (api.source.tests_source.SourceTest)
Completely update a Source. ... FAIL
test_update_bad_cred_type (api.source.tests_source.SourceTest)
Fail update due to bad cred type. ... FAIL
test_update_collide (api.source.tests_source.SourceTest)
Fail update due to name conflict. ... FAIL
test_update_empty_hosts (api.source.tests_source.SourceTest)
Fail update due to empty host array. ... FAIL
test_update_missing_hosts (api.source.tests_source.SourceTest)
Fail update due to missing host array. ... FAIL
test_update_sat_greenpath (api.source.tests_source.SourceTest)
Sat - Valid full update. ... FAIL
test_update_sat_more_than_one_cred (api.source.tests_source.SourceTest)
Sat- Fail update due to multiple hosts. ... FAIL
test_update_sat_more_than_one_hosts (api.source.tests_source.SourceTest)
Sat- Fail update due to multiple hosts. ... FAIL
test_update_sat_range_hosts (api.source.tests_source.SourceTest)
Fail update due to invalid host array. ... FAIL
test_update_sat_with_options (api.source.tests_source.SourceTest)
Sat - Valid full update with options. ... FAIL
test_update_type_passed (api.source.tests_source.SourceTest)
Fail update due to type passed. ... FAIL
test_update_vc_greenpath (api.source.tests_source.SourceTest)
VC - Success full update. ... FAIL
test_update_vc_more_than_one_cred (api.source.tests_source.SourceTest)
VC - Fail more than one cred. ... FAIL
test_update_vc_more_than_one_host (api.source.tests_source.SourceTest)
VC - Fail more than one host. ... FAIL
test_update_vc_range_hosts (api.source.tests_source.SourceTest)
Fail update due to empty host array. ... FAIL

======================================================================
FAIL: test_create_multiple_hosts (api.source.tests_source.SourceTest)
A valid create request with two hosts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 236, in test_create_multiple_hosts
    self.create_expect_201(data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_create_valid_hosts (api.source.tests_source.SourceTest)
Test valid host patterns.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 336, in test_create_valid_hosts
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_delete (api.source.tests_source.SourceTest)
Delete a Source.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 816, in test_delete
    response = self.create_expect_201(data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_double_create (api.source.tests_source.SourceTest)
A duplicate create should fail.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 225, in test_double_create
    response = self.create_expect_201(data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_filter_by_type_list (api.source.tests_source.SourceTest)
List all Source objects filtered by type.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 489, in test_filter_by_type_list
    self.create_expect_201(this_data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_list (api.source.tests_source.SourceTest)
List all Source objects.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 451, in test_list
    self.create_expect_201(this_data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_partial_update (api.source.tests_source.SourceTest)
Partially update a Source.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 796, in test_partial_update
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_partial_update_empty_hosts (api.source.tests_source.SourceTest)
Partial update should succeed with missing hosts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 692, in test_partial_update_empty_hosts
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_partial_update_missing_hosts (api.source.tests_source.SourceTest)
Partial update should succeed with missing hosts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 633, in test_partial_update_missing_hosts
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_partial_update_network_ssl_options_not_allowed (api.source.tests_source.SourceTest)
Partial update should succeed with missing hosts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 652, in test_partial_update_network_ssl_options_not_allowed
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_partial_update_no_hosts_retains_initial_host (api.source.tests_source.SourceTest)
Partial update should keep initial host if no host provided.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 672, in test_partial_update_no_hosts_retains_initial_host
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_retrieve (api.source.tests_source.SourceTest)
Get details on a specific Source by primary key.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 547, in test_retrieve
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_source_create_with_false_scan (api.source.tests_source.SourceTest)
Test creating a source with a valid scan query param of False.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 176, in test_source_create_with_false_scan
    response = self.create_expect_201_with_query(query, data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 118, in create_expect_201_with_query
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_source_create_with_true_scan (api.source.tests_source.SourceTest)
Test creating source with valid scan query param of True.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 187, in test_source_create_with_true_scan
    self.create_expect_201_with_query(query, data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 118, in create_expect_201_with_query
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_successful_net_create (api.source.tests_source.SourceTest)
A valid create request should succeed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 206, in test_successful_net_create
    response = self.create_expect_201(data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_successful_net_create_no_port (api.source.tests_source.SourceTest)
A valid create request should succeed without port.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 215, in test_successful_net_create_no_port
    response = self.create_expect_201(data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_successful_sat_create (api.source.tests_source.SourceTest)
A valid create request should succeed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 993, in test_successful_sat_create
    response = self.create_expect_201(data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_successful_sat_create_with_options (api.source.tests_source.SourceTest)
A valid create request should succeed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 1003, in test_successful_sat_create_with_options
    response = self.create_expect_201(data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_successful_vc_create (api.source.tests_source.SourceTest)
A valid create request should succeed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 857, in test_successful_vc_create
    response = self.create_expect_201(data)
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update (api.source.tests_source.SourceTest)
Completely update a Source.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 576, in test_update
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_bad_cred_type (api.source.tests_source.SourceTest)
Fail update due to bad cred type.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 775, in test_update_bad_cred_type
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_collide (api.source.tests_source.SourceTest)
Fail update due to name conflict.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 606, in test_update_collide
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_empty_hosts (api.source.tests_source.SourceTest)
Fail update due to empty host array.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 731, in test_update_empty_hosts
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_missing_hosts (api.source.tests_source.SourceTest)
Fail update due to missing host array.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 712, in test_update_missing_hosts
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_sat_greenpath (api.source.tests_source.SourceTest)
Sat - Valid full update.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 1060, in test_update_sat_greenpath
    'credentials': [self.sat_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_sat_more_than_one_cred (api.source.tests_source.SourceTest)
Sat- Fail update due to multiple hosts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 1126, in test_update_sat_more_than_one_cred
    'credentials': [self.sat_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_sat_more_than_one_hosts (api.source.tests_source.SourceTest)
Sat- Fail update due to multiple hosts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 1106, in test_update_sat_more_than_one_hosts
    'credentials': [self.sat_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_sat_range_hosts (api.source.tests_source.SourceTest)
Fail update due to invalid host array.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 1147, in test_update_sat_range_hosts
    'credentials': [self.sat_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_sat_with_options (api.source.tests_source.SourceTest)
Sat - Valid full update with options.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 1080, in test_update_sat_with_options
    'credentials': [self.sat_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_type_passed (api.source.tests_source.SourceTest)
Fail update due to type passed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 754, in test_update_type_passed
    'credentials': [self.net_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_vc_greenpath (api.source.tests_source.SourceTest)
VC - Success full update.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 907, in test_update_vc_greenpath
    'credentials': [self.vc_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_vc_more_than_one_cred (api.source.tests_source.SourceTest)
VC - Fail more than one cred.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 947, in test_update_vc_more_than_one_cred
    'credentials': [self.vc_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_vc_more_than_one_host (api.source.tests_source.SourceTest)
VC - Fail more than one host.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 927, in test_update_vc_more_than_one_host
    'credentials': [self.vc_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

======================================================================
FAIL: test_update_vc_range_hosts (api.source.tests_source.SourceTest)
Fail update due to empty host array.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 968, in test_update_vc_range_hosts
    'credentials': [self.vc_cred_for_upload]})
  File "/home/cecarter/rh/quipucords/quipucords/api/source/tests_source.py", line 96, in create_expect_201
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201

----------------------------------------------------------------------
Ran 67 tests in 3.963s

FAILED (failures=34)
make: *** [Makefile:46: test-case] Error 1
